name = "Lekh"
license = "MIT"
licenselink = "https://github.com/invinciblycool/lekh/blob/master/LICENSE.md"
description = "A text focussed and minimal personal portfolio theme, inspired from https://github.com/vegarsti/vegarsti.github.io"
homepage = "https://github.com/invinciblycool/lekh"
tags = ["minimal", "clean", "blog", "responsive", "personal", "simple", "minimalist", "portfolio", "text-focussed", "dark", "dark-mode", "rss"]
features = ["blog", "Clean and minimal", "Responsive", "Social media links", "Markdown", "Text focussed", "Dark mode", "RSS feeds"]
min_version = "0.38"

[author]
  name = "Rahul Tiwari"
  homepage = "https://rtiwari.me/"
